stages:
 - build
 - deploy

maven-build:
  image: maven:3-jdk-11
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/gitlab-ci-demo.jar

deploy-master:
  variables:
    HOST: "165.227.148.165"
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^master$/' 
  before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass
    - echo "Host= $HOST"
  stage: deploy
  script:
    - sshpass -V
    - export SSHPASS=$CI_USER_PASS
    - sshpass -e scp -o StrictHostKeyChecking=no target/gitlab-ci-demo.jar gitlab-ci@$HOST:/home/gitlab-ci
    - sshpass -e ssh -tt -o StrictHostKeyChecking=no gitlab-ci@$HOST sudo mv /home/gitlab-ci/gitlab-ci-demo.jar /opt/java/webapps
    - sshpass -e ssh -tt -o StrictHostKeyChecking=no gitlab-ci@$HOST sudo systemctl restart gitlab-ci-demo.service
